import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { HasLoadedProvider } from "@/components/loadedContext";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <HasLoadedProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </HasLoadedProvider>
    </html>
  );
}
